export { default as CandidateListScreen } from './CandidateListScreen/CandidateListScreen'
export { default as LoginScreen } from './LoginScreen/LoginScreen'
export { default as HomeScreen } from './HomeScreen/HomeScreen'
export { default as InfoScreen } from './InfoScreen/InfoScreen'
export { default as ProfileScreen } from './ProfileScreen/ProfileScreen'
export { default as RegistrationScreen } from './RegistrationScreen/RegistrationScreen'
export { default as WelcomeScreen } from './WelcomeScreen/WelcomeScreen'